/* Generated By:JavaCC: Do not edit this line. ExprEvalConstants.java */
package expreval;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExprEvalConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENTIER = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"**\"",
    "\"(\"",
    "\")\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<ENTIER>",
  };

}
