/* Generated By:JavaCC: Do not edit this line. StringParserConstants.java */
package stringparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StringParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENTIER = 12;
  /** RegularExpression Id. */
  int LETTRE = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"<\"",
    "\">\"",
    "\"*\"",
    "\"~\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<ENTIER>",
    "<LETTRE>",
  };

}
