/* Generated By:JavaCC: Do not edit this line. ExprVerifConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExprVerifConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENTIER = 14;
  /** RegularExpression Id. */
  int IDENTIFIER = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"**\"",
    "\"(\"",
    "\")\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<ENTIER>",
    "<IDENTIFIER>",
  };

}
